### ISSUE TITLE
Omniawrite freezes when pressing escape while the edit order menu is active

### ISSUE THREAD

**Issue by FireFoxUser2222222225** [TorstenDittmann/OmniaWrite#142]
Steps to reproduce:
Open Omniawrite
Click Edit Order
Press escape.

The program does respond, but all the buttons are locked up. I suspect this is due to a global "freeze" when the menu is opened. To prevent the pressing of other buttons over the new UI.
EDIT: Normally closing the window as well causes an issue.

**Comment by TorstenDittmann** [comment]
Fixed, update is releasing right now 🙂
