### ISSUE TITLE
[modal] unsupported browser warning

### ISSUE THREAD

**Issue by TorstenDittmann** [TorstenDittmann/OmniaWrite#40]
When the user opens the WebApp, we should check if the used browser is none of:

- Any chromium based browser
- Firefox
- Safari/WebKit

The user should be able to dismiss this warning for the session or X days. Using cookies for this might be the smartest approach.
Content of the modal, should be suggesting to use Brave Browser or the desktop apps.

We also need to check if the user is on Electron or Capacitor to not show this message at all. I am not quite sure about their user agents right now.

**Comment by syentix** [comment]
I could try doing this. How would you like it implemented? I would add a function to the utils file that returns true or false for web browser that could be used and maybe add a warning on the start page?

**Comment by TorstenDittmann** [comment]
I think a utils function would be enough, I can do the actual UI part later 👍

**Comment by syentix** [comment]
Hey I actually worked on the UI and am currently working on the cookie. I can try to setup the cookie today and then then setup a pr so we can discuss some more details.

**Comment by TorstenDittmann** [comment]
@allcontributors please add @syentix for code.

Thanks for the work! 👏

**Comment by syentix** [comment]
It was really fun, I'd be glad to work on some more stuff :) Oh and sorry for the rocky start, still getting used to all this!
