### ISSUE TITLE
Scene tab is not updated when scene is renamed

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#50]
**Describe the bug**
When I rename a scene, the scene's tab continues to show the old name.

**To Reproduce**
1. Create a scene, or select an existing scene.
2. Add it to the tab list.
3. Rename the scene.
4. Observe that the tab still shows the original name.

**Expected behavior**
The tab is updated with the new name.

**Screenshots**
![image](https://user-images.githubusercontent.com/69065091/89841688-da8fed00-db30-11ea-8782-a2fb215d4366.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu
 - Browser: Chrome 84

**Comment by TorstenDittmann** [comment]
Damn, I implemented the tabs a long time ago and the implementation is very bad to be fair.

This also requires a breaking change now, since I stored links & titles instead of id's. So part of this will also be a migration script 👍
