### ISSUE TITLE
Undo/Redo buttons do not update word count

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#52]
**Describe the bug**
The word count is not updated after using the Undo and Redo buttons.

**To Reproduce**
1. Open or create a scene with some text in it.
2. Select and delete a few words. The word count decreases.
3. Press Undo button.
4. Observe that the word count does not go back.
5. Start typing again: the word count gets updated and is accurate.

**Expected behavior**
The word count should be updated (immediately or with a delay) after pressing Undo or Redo buttons.

**Comment by TorstenDittmann** [comment]
Seemed like they didnt even change any scenes in the store. Got fixed with https://github.com/TorstenDittmann/OmniaWrite/commit/d1d3bb55ff665a3a4375752ce9f1cad3dc323b53

Nice catch 🥳
