### ISSUE TITLE
[editor] Deleting a paragraph cannot be undone

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#60]
**Describe the bug**
Undo button cannot undo the removal of a block of text.

**To Reproduce**
1. Create a scene with 2 non-empty paragraphs.
2. Delete the first paragraph.
3. Press Undo button or ctrl+Z.
4. Observe that step 3 has no visible effect: paragraph is not restored.

Redo button has some surprising effect though:
1. Create a scene with 2 non-empty paragraphs.
2. Delete the first paragraph.
3. Press Undo _twice_ then Redo _once_.
4. Observe that the deleted block's text is appended twice to the last paragraph.

**Expected behavior**
Ctrl+Z or Undo button restore the deleted block. Ctrl+Y or Redo button delete it again.

**Comment by TorstenDittmann** [comment]
How many steps back do you think is appropriate?

I think we can push the previous content after saving/creating or deleting a block to an array and shift the index on undo and redo.

I think that ~10 steps are doable.

**Comment by AntonyBoucher** [comment]
10 steps sounds good enough. We'll see in practice if more are needed.

**Comment by TorstenDittmann** [comment]
Fixed 🥳
