### ISSUE TITLE
Buttons clutter the editor on narrow displays

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#61]
**Describe the bug**
When the screen is < 960px wide, buttons are visible below every block.

**Expected behavior**
Button appear under the active paragraph only. Or they appear once, at the bottom of the screen, and apply to the active block (or last block, if none is active).

**Screenshots**
![image](https://user-images.githubusercontent.com/69065091/90323501-62a23800-df1f-11ea-9004-020cf333415b.png)

**Comment by TorstenDittmann** [comment]
Fixed.
