### ISSUE TITLE
Editor i18n

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#62]
**Describe the bug**
Editor UI is in English no matter what language is selected in Settings:
- "Let's write an awesome story!" placeholders
- "Paragraph", "Quote", "Heading", "Delete" button tooltips
- "Are you sure? OK Cancel" block delete dialog

**Expected**
The whole UI is in the language selected in Settings.

**Comment by TorstenDittmann** [comment]
Fixed.
