### ISSUE TITLE
[editor] Inactive heading block is the same color as active heading block

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#63]
**Describe the bug**
When a block is active, other blocks are greyed out except headings, which remain the same color as the active block.

**Expected behavior**
Heading blocks are greyed out when inactive.

**Screenshots**
![image](https://user-images.githubusercontent.com/69065091/90323713-4b187e80-df22-11ea-816a-cc7417739c7a.png)

**Comment by TorstenDittmann** [comment]
Fixed 🥳
