### ISSUE TITLE
Text pasted from other apps is not sanitized

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#64]
**Describe the bug**
When text or "content" is pasted into the editor from another app (browser, Word, VS Code, etc) its formatting is imported along with it, even if the editor does not support it.

**To Reproduce**
1. Select some content from a website, and paste it into a paragraph.
2. Observe that the text keeps its original formatting, and elements like links, images and videos are displayed inside OmniaWrite.
3. Switch scenes back and forth; the content is eventually sanitized.

**Expected behavior**
Pasted text should be scrubbed of all unsupported formatting, i.e all tags except \<b>, \<i>, \<u>. Line breaks should also be handled somehow, as they are (currently) not allowed inside paragraphs.

**Screenshots**
![image](https://user-images.githubusercontent.com/69065091/90323814-91baa880-df23-11ea-8e3f-280f10cfcd70.png)

**Comment by TorstenDittmann** [comment]
Fixed 🥳
