### ISSUE TITLE
Inserting a block above the first one

### ISSUE THREAD

**Issue by AntonyBoucher** [TorstenDittmann/OmniaWrite#69]
We have buttons to insert new blocks *below* existing blocks. But none to insert a block *above* the first block.

**Suggestion:** Show buttons below the scene title when the mouse hovers over the space.

![image](https://user-images.githubusercontent.com/69065091/90340114-fec94f00-dfb2-11ea-8910-b70fc0315ec7.png)

**Comment by TorstenDittmann** [comment]
Fixed 🥳
