### ISSUE TITLE
Android Client

### ISSUE THREAD

**Issue by fabiopolancoe** [TorstenDittmann/OmniaWrite#80]
Hi, I was looking for a native Android client, but it was unsuccessful, I don't know if it already exists but it's not published on releases and that's why I'm opening this Issue.

I guess i would try to compile it myself, but i honestly don't know how to do it. I think it's a great project, I already installed the Linux Desktop application and it's working perfectly. So thanks in advance :grin:

**Comment by TorstenDittmann** [comment]
Oh yeah, I never really linked it here on GitHub 😅

Keep in mind that the currently published Android App is a little bit limited and a new update to version 1.1 with lots of new features is nearly done.

Here is the link: https://play.google.com/store/apps/details?id=com.omniawrite.app

**Comment by fabiopolancoe** [comment]
Thank you very much, I had actually searched for OmniaWrite on the Play Store, but couldn't find it, that's why I asked here. When I went to the link, it tells me that it is not compatible with my smartphone, so I will continue to use the web version on it. Thank you very much anyway, greetings!

**Comment by TorstenDittmann** [comment]
Interesting, do you mind sharing what Device you are using?

**Comment by fabiopolancoe** [comment]
Sure, I'm using and LG-H500 (LG Magna) with Android 5.0.1 😀

**Comment by TorstenDittmann** [comment]
Everything under Android 7.0 could be tricky, I will give it a try and see what is possible 👍

**Comment by fabiopolancoe** [comment]
Thank you very much, it is very kind of you to support me, I will definitely give OmniaWrite a star 😄
