### ISSUE TITLE
Some strings are not displayed in Spanish

### ISSUE THREAD

**Issue by dennistobar** [TorstenDittmann/OmniaWrite#93]
**Describe the bug**
After create a new Scene, the string `Let's write an awesome story!` and the dialog to confirm delete a paragraph are displayed in English.

**To Reproduce**
1. Change the language to Spanish
2. Click on New Scene (when is available)
3. See the string in new page

**Expected behavior**
Show the string "¡Vamos a escribir una historia asombrosa!" and "¿Estás seguro?"

**Screenshots**
![Captura de pantalla de 2020-09-24 22-32-40](https://user-images.githubusercontent.com/1218182/94216483-e273d880-feb5-11ea-9a09-6dd7e5b5fe89.png)
![Captura de pantalla de 2020-09-24 22-32-25](https://user-images.githubusercontent.com/1218182/94216487-e3a50580-feb5-11ea-9e94-76d020c6af8a.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 85

**Additional context**
I think the problem is in omnia-editor [maybe here](https://github.com/TorstenDittmann/omnia-editor/blob/14d954f87d84ebe6fdd1c0a02aac5dd5b155d518/src/Editor.svelte#L17), I'm unsure about that, and I can read TypeScript but I can't write code fluently.

**Comment by TorstenDittmann** [comment]
Good catch!

This is actually implemted and I missed 2 strings. There is a `i18n` store that is being handed the translation from OmniaWrite. It just needs to have the correct variable set:
https://github.com/TorstenDittmann/omnia-editor/blob/master/src/Editor.svelte#L116
https://github.com/TorstenDittmann/omnia-editor/blob/master/src/Editor.svelte#L110
And these can be deleted:
https://github.com/TorstenDittmann/omnia-editor/blob/master/src/Editor.svelte#L17-L18

If you want, you can create a PR at omnia-editor :-)
